/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export type ProfilePublicationDataStruct = {
  collectLimit: BigNumberish;
  currentCollects: BigNumberish;
  amount: BigNumberish;
  currency: string;
  recipient: string;
  referralFee: BigNumberish;
  followerOnly: boolean;
};

export type ProfilePublicationDataStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  string,
  string,
  number,
  boolean
] & {
  collectLimit: BigNumber;
  currentCollects: BigNumber;
  amount: BigNumber;
  currency: string;
  recipient: string;
  referralFee: number;
  followerOnly: boolean;
};

export interface LensLimitedFeeCollectModuleInterface extends utils.Interface {
  functions: {
    "HUB()": FunctionFragment;
    "MODULE_GLOBALS()": FunctionFragment;
    "getPublicationData(uint256,uint256)": FunctionFragment;
    "initializePublicationCollectModule(uint256,uint256,bytes)": FunctionFragment;
    "processCollect(uint256,address,uint256,uint256,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "HUB"
      | "MODULE_GLOBALS"
      | "getPublicationData"
      | "initializePublicationCollectModule"
      | "processCollect"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "HUB", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MODULE_GLOBALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPublicationData",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initializePublicationCollectModule",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "processCollect",
    values: [BigNumberish, string, BigNumberish, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "HUB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MODULE_GLOBALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublicationData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializePublicationCollectModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processCollect",
    data: BytesLike
  ): Result;

  events: {};
}

export interface LensLimitedFeeCollectModule extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LensLimitedFeeCollectModuleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    HUB(overrides?: CallOverrides): Promise<[string]>;

    MODULE_GLOBALS(overrides?: CallOverrides): Promise<[string]>;

    getPublicationData(
      profileId: BigNumberish,
      pubId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[ProfilePublicationDataStructOutput]>;

    initializePublicationCollectModule(
      profileId: BigNumberish,
      pubId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    processCollect(
      referrerProfileId: BigNumberish,
      collector: string,
      profileId: BigNumberish,
      pubId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  HUB(overrides?: CallOverrides): Promise<string>;

  MODULE_GLOBALS(overrides?: CallOverrides): Promise<string>;

  getPublicationData(
    profileId: BigNumberish,
    pubId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<ProfilePublicationDataStructOutput>;

  initializePublicationCollectModule(
    profileId: BigNumberish,
    pubId: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  processCollect(
    referrerProfileId: BigNumberish,
    collector: string,
    profileId: BigNumberish,
    pubId: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    HUB(overrides?: CallOverrides): Promise<string>;

    MODULE_GLOBALS(overrides?: CallOverrides): Promise<string>;

    getPublicationData(
      profileId: BigNumberish,
      pubId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<ProfilePublicationDataStructOutput>;

    initializePublicationCollectModule(
      profileId: BigNumberish,
      pubId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    processCollect(
      referrerProfileId: BigNumberish,
      collector: string,
      profileId: BigNumberish,
      pubId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    HUB(overrides?: CallOverrides): Promise<BigNumber>;

    MODULE_GLOBALS(overrides?: CallOverrides): Promise<BigNumber>;

    getPublicationData(
      profileId: BigNumberish,
      pubId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initializePublicationCollectModule(
      profileId: BigNumberish,
      pubId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    processCollect(
      referrerProfileId: BigNumberish,
      collector: string,
      profileId: BigNumberish,
      pubId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    HUB(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MODULE_GLOBALS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPublicationData(
      profileId: BigNumberish,
      pubId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initializePublicationCollectModule(
      profileId: BigNumberish,
      pubId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    processCollect(
      referrerProfileId: BigNumberish,
      collector: string,
      profileId: BigNumberish,
      pubId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
