/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export declare namespace DataTypes {
  export type MetadataStruct = {
    originalContract: string;
    profileId: BigNumberish;
    pubId: BigNumberish;
    collectModule: string;
  };

  export type MetadataStructOutput = [string, BigNumber, BigNumber, string] & {
    originalContract: string;
    profileId: BigNumber;
    pubId: BigNumber;
    collectModule: string;
  };
}

export interface LensDataTokenInterface extends utils.Interface {
  functions: {
    "collect(bytes)": FunctionFragment;
    "getContentURI()": FunctionFragment;
    "getDataTokenOwner()": FunctionFragment;
    "getFeeRecipient()": FunctionFragment;
    "getMetadata()": FunctionFragment;
    "isCollected(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "collect"
      | "getContentURI"
      | "getDataTokenOwner"
      | "getFeeRecipient"
      | "getMetadata"
      | "isCollected"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "collect", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getContentURI",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDataTokenOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMetadata",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isCollected", values: [string]): string;

  decodeFunctionResult(functionFragment: "collect", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getContentURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDataTokenOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCollected",
    data: BytesLike
  ): Result;

  events: {};
}

export interface LensDataToken extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LensDataTokenInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    collect(
      encodedCollectWithSigData: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getContentURI(overrides?: CallOverrides): Promise<[string]>;

    getDataTokenOwner(overrides?: CallOverrides): Promise<[string]>;

    getFeeRecipient(overrides?: CallOverrides): Promise<[string]>;

    getMetadata(
      overrides?: CallOverrides
    ): Promise<[DataTypes.MetadataStructOutput]>;

    isCollected(user: string, overrides?: CallOverrides): Promise<[boolean]>;
  };

  collect(
    encodedCollectWithSigData: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getContentURI(overrides?: CallOverrides): Promise<string>;

  getDataTokenOwner(overrides?: CallOverrides): Promise<string>;

  getFeeRecipient(overrides?: CallOverrides): Promise<string>;

  getMetadata(
    overrides?: CallOverrides
  ): Promise<DataTypes.MetadataStructOutput>;

  isCollected(user: string, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    collect(
      encodedCollectWithSigData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    getContentURI(overrides?: CallOverrides): Promise<string>;

    getDataTokenOwner(overrides?: CallOverrides): Promise<string>;

    getFeeRecipient(overrides?: CallOverrides): Promise<string>;

    getMetadata(
      overrides?: CallOverrides
    ): Promise<DataTypes.MetadataStructOutput>;

    isCollected(user: string, overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    collect(
      encodedCollectWithSigData: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getContentURI(overrides?: CallOverrides): Promise<BigNumber>;

    getDataTokenOwner(overrides?: CallOverrides): Promise<BigNumber>;

    getFeeRecipient(overrides?: CallOverrides): Promise<BigNumber>;

    getMetadata(overrides?: CallOverrides): Promise<BigNumber>;

    isCollected(user: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    collect(
      encodedCollectWithSigData: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getContentURI(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDataTokenOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFeeRecipient(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMetadata(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isCollected(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
